apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-ordering
  labels:
    app: meal-ordering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meal-ordering
  template:
    metadata:
      labels:
        app: meal-ordering
    spec:
      containers:
        - name: meal-ordering
          image: pavansaikumar49221/meal-ordering:latest
          ports:
            - containerPort: 80
